version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_DB=my_store
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80

  mysql:
    image: mysql:5
    container_name: mysql
    restart: always
    environment:
      - MYSQL_DATABASE='my_store'
      - MYSQL_USER='duckycoyote'
      - MYSQL_ROOT_PASSWORD='admin123'
      - MYSQL_PASSWORD='admin123'
      - MYSQL_PORT='3306'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - mysql:/var/lib/mysql
volumes:
  mysql:
    driver: local
